"""change table agrs

Revision ID: 7e0769251641
Revises: 00954709134f
Create Date: 2025-05-16 19:52:32.912145

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "7e0769251641"
down_revision: Union[str, None] = "00954709134f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_game_genre_association_game_id_genre_id"),
        "game_genre_association",
        ["game_id", "genre_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_game_genre_association_game_id_genre_id"),
        "game_genre_association",
        type_="unique",
    )
    # ### end Alembic commands ###
