"""change relationship with tables

Revision ID: 2f461e7ecdff
Revises: bdbbcd96507b
Create Date: 2025-05-15 17:06:08.816251

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f461e7ecdff"
down_revision: Union[str, None] = "bdbbcd96507b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "games",
        sa.Column(
            "rating_id",
            sa.Integer(),
            nullable=True,
        ),
    )
    op.create_foreign_key(
        op.f("fk_games_rating_id_meta_game_ratings"),
        "games",
        "meta_game_ratings",
        ["rating_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(
        "fk_meta_game_ratings_game_id_games",
        "meta_game_ratings",
        type_="foreignkey",
    )
    op.drop_column(
        "meta_game_ratings",
        "game_id",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meta_game_ratings",
        sa.Column(
            "game_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_foreign_key(
        "fk_meta_game_ratings_game_id_games",
        "meta_game_ratings",
        "games",
        ["game_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_games_rating_id_meta_game_ratings"),
        "games",
        type_="foreignkey",
    )
    op.drop_column("games", "rating_id")
    # ### end Alembic commands ###
