"""create tables

Revision ID: 1cf5ebc13769
Revises:
Create Date: 2025-05-14 22:57:16.875361

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1cf5ebc13769"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "games",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "title",
            sa.String(length=120),
            nullable=False,
        ),
        sa.Column(
            "description",
            sa.Text(),
            server_default="",
            nullable=False,
        ),
        sa.Column(
            "image_url",
            sa.String(),
            nullable=True,
        ),
        sa.Column(
            "platforms",
            sa.JSON(),
            nullable=False,
        ),
        sa.Column(
            "release_date",
            sa.Date(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk_games"),
        ),
    )
    op.create_index(
        op.f("ix_games_title"),
        "games",
        ["title"],
        unique=False,
    )
    op.create_table(
        "meta_game_ratings",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "value",
            sa.Float(),
            server_default="0.0",
            nullable=False,
        ),
        sa.Column(
            "game_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
            name=op.f(
                "fk_meta_game_ratings_game_id_games",
            ),
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk_meta_game_ratings"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("meta_game_ratings")
    op.drop_index(op.f("ix_games_title"), table_name="games")
    op.drop_table("games")
    # ### end Alembic commands ###
