"""change value type in ratings table

Revision ID: bdbbcd96507b
Revises: 1cf5ebc13769
Create Date: 2025-05-15 15:42:20.360472

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bdbbcd96507b"
down_revision: Union[str, None] = "1cf5ebc13769"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "meta_game_ratings",
        "value",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Integer(),
        existing_nullable=False,
        existing_server_default=sa.text("'0'::double precision"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "meta_game_ratings",
        "value",
        existing_type=sa.Integer(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
        existing_server_default=sa.text("'0'::double precision"),
    )
    # ### end Alembic commands ###
